[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
defi_101 = "8aDyKXbYswuR4Czq8q6PCtuiYTqSrNn776z4LLHA47uu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "deno test -E -R -N tests/defi-101.ts"
